name: Deploy to Hostinger

on:
  push:
    branches: [main] # or your production branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "23" # or your preferred version

      - name: Install dependencies
        run: npm install

      - name: Build production app
        run: npm run build

      - name: Deploy to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.HOSTINGER_FTP_SERVER }}
          username: ${{ secrets.HOSTINGER_FTP_USERNAME }}
          password: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: /home/u917895091/domains/alsalam-loerrach.org/public_html/ # or your Hostinger directory
